### ISSUE TITLE
奔饭交通安全法

### ISSUE THREAD

**Issue by Colacon** [wandleshen/XuejunSurviveManual#5]
在饭点铃声打响时起身奔向食堂大概是大部分学军人的本能，毕竟纵使学校管理层（没有特指戴姓老师）把头都挠秃了，每日午时奔饭大道上的风景依旧靓丽如初。所谓道高一尺魔高一丈，在监管者与干饭大众无止境的斗智斗勇过程中，学军针对奔饭的管理制度时有升级，防范意识跟不上时代进步的结果只能是亲人两行泪。笔者这一届的学军干饭人大约曾经历了：戴老师哨子执法时代，全明星暗影刺客时代，值周生大屏曝光时代等数个界线并不分明的时代。虽然随着时代的进步，各条道路的危险系数都有所上升，不同道路的限速还是会有所不同。传统的奔饭大道如今已是戒备森严，只有艺高人胆大者能够放心超速通行；高架路面作为曾经的管理灰色地带，也因为长期流量过大而被监管者盯上；操场与教学区之间的大道（没记错的话叫思齐路）在笔者毕业时暂且还是法外之地，其未来的命运掌握在各位的手中。至于诸如变速跑或是在超速10%的临界点左右横跳之类的驾驶技巧，是将入狱几率的百分之五十交给了监管者当日的心情决定。所以，如果今后你在食堂门口又见到了一脸严肃的值班老师，不妨请ta吃一支巧乐兹。

**Comment by wandleshen** [comment]
？
