### ISSUE TITLE
修正 README.md 链接错误

### ISSUE THREAD

**Issue by cosing** [wandleshen/XuejunSurviveManual#8]
关于
`[恋爱指北](https://github.com/wandleshen/XuejunSurviveManual/blob/master/GuideBook/ElecroBoom/BadRoamance.md)`应该改成`[恋爱指北](https://github.com/wandleshen/XuejunSurviveManual/blob/master/GuideBook/ElectroBoom/BadRomance.md)`

BadRoamance多了a
ElecroBoom少了t

或者说，作者是故意的x

**Comment by wandleshen** [comment]
感谢反馈，没想到当初玩票性质的项目还会有新的访客。确实是笔误，现已修正。总之再次感谢反馈！
